const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  lock: (opts) => ipcRenderer.invoke("frame:lock", opts),
  clear: () => ipcRenderer.invoke("frame:clear"),
  cancel: () => ipcRenderer.invoke("frame:cancel"),
  health: () => ipcRenderer.invoke("frame:health"),
  retryRemaining: () => ipcRenderer.invoke("frame:retry"),
  restorePrevious: () => ipcRenderer.invoke("frame:restore"),
  setReadingMode: value => ipcRenderer.invoke("frame:readingMode", value),
  moveSelectionToCursor: () => ipcRenderer.invoke("frame:recenter"),
  setToolbarHeight: value => ipcRenderer.send("frame:height", value),
  inspectBubble: key => ipcRenderer.invoke("bubble:inspect", key),
  reocrBubble: key => ipcRenderer.invoke("bubble:ocr", key),
  mangaOcrBubble: key => ipcRenderer.invoke("bubble:manga-ocr", key),
  retranslateBubble: data => ipcRenderer.invoke("bubble:translate", data),
  editorOpen: value => ipcRenderer.send("overlay:editor", value),
  dismissBubble: key => ipcRenderer.send("bubble:dismiss", key),
  glassRegions: regions => ipcRenderer.send("glass:regions", regions),
  onGlassFrame: cb => ipcRenderer.on("glass:frame", (_e, data) => cb(data)),
  onGlassMotion: cb => ipcRenderer.on("glass:motion", (_e, data) => cb(data)),
  reveal: () => ipcRenderer.invoke("frame:reveal"),
  preferences: (prefs) => ipcRenderer.send("frame:preferences", prefs),
  setInteractionLocked: (value) => ipcRenderer.send("frame:interact", value),
  resizeTo: (x, y, w, h, anchor) => ipcRenderer.invoke("frame:resizeTo", x, y, w, h, anchor),
  getBounds: () => ipcRenderer.invoke("frame:getBounds"),
  quit: () => ipcRenderer.invoke("frame:quit"),
  configuration: () => ipcRenderer.invoke("frame:configuration"),
  hitRegions: (regions) => ipcRenderer.send("win:hitRegions", regions),
  dragging: (active) => ipcRenderer.send("win:dragging", active),
  onStatus: (cb) => ipcRenderer.on("frame:status", (_e, data) => cb(data)),
  onRecovery: cb => ipcRenderer.on("frame:recovery", (_e, data) => cb(data)),
  onReadingState: cb => ipcRenderer.on("frame:readingState", (_e, data) => cb(data)),
  onSelectionState: cb => ipcRenderer.on("selection:state", (_e, data) => cb(data)),
  onReveal: (cb) => ipcRenderer.on("frame:reveal", (_e, data) => cb(data)),
  onHotkeyLock: (cb) => ipcRenderer.on("frame:hotkeyLock", () => cb()),
  onOverlayAdd: (cb) => ipcRenderer.on("overlay:add", (_e, bubbles) => cb(bubbles)),
  onOverlayBegin: (cb) => ipcRenderer.on("overlay:begin", (_e, data) => cb(data)),
  onOverlayRegions: (cb) => ipcRenderer.on("overlay:regions", (_e, data) => cb(data)),
  onOverlayFinish: (cb) => ipcRenderer.on("overlay:finish", (_e, data) => cb(data)),
  onOverlayRestore: cb => ipcRenderer.on("overlay:restore", (_e, data) => cb(data)),
  onOverlayStale: cb => ipcRenderer.on("overlay:stale", (_e, data) => cb(data)),
  onOverlayReveal: (cb) => ipcRenderer.on("overlay:reveal", (_e, data) => cb(data)),
  onOverlayPreferences: (cb) => ipcRenderer.on("overlay:preferences", (_e, data) => cb(data)),
  onOverlayProgress: (cb) => ipcRenderer.on("overlay:progress", (_e, data) => cb(data)),
  onOverlayClear: (cb) => ipcRenderer.on("overlay:clear", () => cb()),
});
