const {app,BrowserWindow,ipcMain,nativeImage}=require('electron');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');
app.setPath('userData',path.join(root,'.qa','electron-tests'));
app.disableHardwareAcceleration();
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check,timeout=3000) {
  const start=Date.now();
  while(Date.now()-start<timeout) {if(await check()) return;await delay(20);}
  throw new Error('Timed out waiting for renderer state');
}
async function snapshot(win,name) {
  // Hidden windows can retain an older compositor frame until explicitly painted.
  await win.webContents.executeJavaScript(`Promise.all([...document.images].filter(img=>img.getAttribute('src')).map(img=>img.decode()))`);
  win.webContents.invalidate();await win.webContents.capturePage();await delay(80);
  fs.writeFileSync(path.join(root,'.qa',name),(await win.webContents.capturePage()).toPNG());
}
app.whenReady().then(async()=>{
  let win;
  try {
    const dismissedKeys=[];
    ipcMain.on('bubble:dismiss',(_event,key)=>dismissedKeys.push(key));
    win=new BrowserWindow({width:1000,height:740,frame:false,show:false,webPreferences:{backgroundThrottling:false,preload:path.join(root,'preload.js')}});
    await win.loadFile(path.join(root,'renderer/overlay.html'));
    const evaluate=code=>win.webContents.executeJavaScript(code,true);
    await evaluate(`document.body.style.backgroundImage=${JSON.stringify('url('+pathToFileURL(path.join(root,'.qa/fixture.png')).href+')')}`);
    const bubbles=JSON.parse(fs.readFileSync(path.join(root,'.qa/layout.json'),'utf8')).map(b=>({...b,job:1,target:b.id===5?'en':'zh-CN'}));
    const begin={job:1,mode:'smart',fontScale:1,target:'zh-CN',rect:{x:0,y:50,width:1000,height:680},toolbar:{x:0,y:0,width:680,height:192}};
    win.webContents.send('overlay:begin',begin);
    win.webContents.send('overlay:regions',{job:1,bubbles});
    win.webContents.send('overlay:add',bubbles);
    await delay(200);
    const metrics=await evaluate(`Array.from(document.querySelectorAll('.bubble')).map(el=>{const c=el.querySelector('.content'),t=el.querySelector('.copy'),r=el.getBoundingClientRect(),tr=t.getBoundingClientRect();return {mode:el.className,font:parseFloat(getComputedStyle(t).fontSize),clipped:el.classList.contains('inplace')&&(tr.width>c.clientWidth+.5||tr.height>c.clientHeight+.5),inside:r.x>=0&&r.y>=0&&r.right<=innerWidth&&r.bottom<=innerHeight,text:t.textContent,vertical:getComputedStyle(t).writingMode};})`);
    assert.equal(metrics.length,6);
    assert(metrics.every(m=>!m.clipped && m.inside && m.font>=14));
    assert(metrics[2].mode.includes('reading'),'Long text must be readable in a card');
    assert(metrics[3].mode.includes('inplace'),'Flat dark fill should stay in place');
    assert(metrics[4].mode.includes('reading'),'Texture must not be erased');
    assert.equal(metrics[5].vertical,'horizontal-tb');
    await snapshot(win,'after-smart.png');
    fs.writeFileSync(path.join(root,'.qa/renderer-metrics.json'),JSON.stringify(metrics,null,2));
    // Assert real provider/OCR output too when the opt-in benchmark has run.
    const livePath=path.join(root,'.qa/live-fixture.json');
    if(fs.existsSync(livePath)) {
      const live=JSON.parse(fs.readFileSync(livePath,'utf8'));
      win.webContents.send('overlay:begin',{...begin,job:10});
      win.webContents.send('overlay:add',live.bubbles.map(b=>({...b,job:10,target:'zh-CN'})));
      await delay(80);
      assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),6);
      await snapshot(win,'after-live.png');
      win.webContents.send('overlay:begin',begin);win.webContents.send('overlay:add',bubbles);await delay(80);
    }
    // Use Chromium input events confined to this hidden renderer; no system mouse.
    const point=await evaluate(`(()=>{const r=document.querySelectorAll('.bubble')[0].getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`);
    win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...point});
    win.webContents.sendInputEvent({type:'mouseMove',x:point.x+120,y:point.y+80,modifiers:['leftButtonDown']});
    win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,x:point.x+120,y:point.y+80});
    await delay(80);
    assert(await evaluate(`document.querySelector('.bubble').classList.contains('reading')`),'Dragging restores source and detaches a card');
    await evaluate(`document.querySelector('.bubble .original').click()`);
    assert(await evaluate(`document.querySelector('.bubble').classList.contains('showing-original')`));
    win.webContents.send('overlay:reveal',true);await delay(30);
    assert.equal(await evaluate(`getComputedStyle(document.querySelector('.bubble')).visibility`),'hidden');
    win.webContents.send('overlay:reveal',false);
    win.webContents.send('overlay:preferences',{mode:'cards',fontScale:1.5});await delay(100);
    assert.equal(await evaluate(`document.querySelectorAll('.reading').length`),6);
    await snapshot(win,'after-cards.png');
    await evaluate(`document.querySelector('.bubble button[aria-label="关闭此译文"]').click()`);
    await until(()=>dismissedKeys.includes('1:0'));
    assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),5);
    win.webContents.send('overlay:add',[bubbles[0]]);await delay(20);
    assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),5,'Closed item cannot reappear');
    win.webContents.send('overlay:begin',{...begin,job:2});await delay(20);
    assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),0,'Repeating selection replaces old results');
    win.webContents.send('overlay:clear');
    win.webContents.send('overlay:add',[{...bubbles[0],job:2}]);await delay(20);
    assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),0,'Late result after clear ignored');
    win.webContents.send('overlay:begin',{...begin,job:3});
    win.webContents.send('overlay:add',[{...bubbles[0],job:3}]);await delay(20);
    win.webContents.send('overlay:preferences',{mode:'smart',fontScale:1});
    // Very long text remains scrollable; smaller displays keep cards in bounds.
    win.setSize(420,360);
    win.webContents.send('overlay:add',[{...bubbles[0],id:9,job:3,x:370,y:300,w:25,h:20,translated:'长段译文。'.repeat(160)}]);await delay(100);
    assert(await evaluate(`(()=>{const e=[...document.querySelectorAll('.bubble')].at(-1),c=e.querySelector('.content'),r=e.getBoundingClientRect();return r.right<=innerWidth&&r.bottom<=innerHeight&&c.scrollHeight>c.clientHeight&&getComputedStyle(c).overflowY==='auto'})()`));
    win.webContents.send('overlay:finish',{job:3,success:true,completed:2,total:2});
    win.webContents.send('overlay:add',[{...bubbles[0],id:10,job:3}]);await delay(30);
    assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),2,'Finished batch rejects late results');
    await testEditor(win,bubbles[0],begin,dismissedKeys);
    await testFrame();
    win.close();
    console.log('PASS: overlay layouts, drag/reveal/clear, editor/reOCR/save/errors/races, rollback/retry/stale, fixed toolbar/recovery/watch/glass controls');
    app.exit(0);
  } catch(error) {console.error(error);app.exit(1);}
});

async function testEditor(win,base,begin,dismissedKeys) {
  const evaluate=code=>win.webContents.executeJavaScript(code,true);
  const send=async(channel,data)=>{win.webContents.send('overlay:'+channel,data);await delay(30);};
  win.setSize(1000,740);await send('clear');
  let current={...base,job:21,key:'editor-21',text:'今日はいい天気ですね。',translated:'今天天气真好。'};
  const image=nativeImage.createFromPath(path.join(root,'.qa/fixture.png')).crop({x:Math.round(base.x),y:Math.round(base.y),width:Math.round(base.w),height:Math.round(base.h)}).toDataURL();
  let translateMode='error',resolveTranslate,resolveInspect,inspectDeferred=false,translateCalls=0,lastPayload;
  let inspectionSource='ja',mangaAvailable=true,healthDeferred=false;
  let modalOpen=false,hitRegions=[];
  const modalListener=(event,value)=>{if(event.sender===win.webContents) modalOpen=value;};
  const hitsListener=(event,value)=>{if(event.sender===win.webContents) hitRegions=value;};
  ipcMain.on('overlay:editor',modalListener);ipcMain.on('win:hitRegions',hitsListener);
  ipcMain.handle('frame:health',()=>healthDeferred ? new Promise(()=>{}) : {manga_ocr:mangaAvailable});
  const inspection=()=>({text:current.text,translated:current.translated,image,source:inspectionSource,target:'zh-CN',provider:'DeepSeek'});
  ipcMain.handle('bubble:inspect',()=>inspectDeferred ? new Promise(resolve=>{resolveInspect=resolve;}) : inspection());
  ipcMain.handle('bubble:ocr',()=>({text:'今日は本当にいい天気ですね。'}));
  ipcMain.handle('bubble:manga-ocr',()=>mangaAvailable ? {text:'今日はきっといい天気ですね。'} : {error:'尚未安装日漫精读模型'});
  ipcMain.handle('bubble:translate',(_event,data)=>{
    translateCalls++;lastPayload=data;
    if(translateMode==='deferred') return new Promise(resolve=>{resolveTranslate=resolve;});
    if(translateMode==='error') return {error:'测试：原翻译服务暂时不可用'};
    current={...current,text:data.text,translated:'今天的天气真的很好。'};
    return {bubble:current};
  });
  const open=async()=>{
    await evaluate(`document.querySelector('.edit').click()`);
    await until(()=>evaluate(`!document.getElementById('editor-save').disabled`));
  };
  await send('begin',{...begin,job:21,mode:'cards'});await send('add',[current]);
  await send('finish',{job:21,success:true,completed:1,total:1});
  const point=await evaluate(`(()=>{const r=document.querySelector('.copy').getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`);
  win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...point});
  win.webContents.sendInputEvent({type:'mouseMove',x:point.x+65,y:point.y+45,modifiers:['leftButtonDown']});
  win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,x:point.x+65,y:point.y+45});await delay(50);
  await evaluate(`document.querySelector('.original').click()`);
  const position=await evaluate(`({x:document.querySelector('.bubble').offsetLeft,y:document.querySelector('.bubble').offsetTop})`);
  healthDeferred=true;await open();
  assert.equal(await evaluate(`document.getElementById('editor-source').disabled`),false,'Slow health check must not block editing');
  assert.equal(await evaluate(`document.getElementById('editor-manga-ocr').disabled`),false,'Slow health check must not block Manga OCR action');
  await evaluate(`document.getElementById('editor-manga-ocr').click()`);
  await until(()=>evaluate(`document.getElementById('editor-source').value==='今日はきっといい天気ですね。'`));
  await evaluate(`document.getElementById('editor-cancel').click()`);
  healthDeferred=false;await open();
  assert.equal(await evaluate(`document.activeElement.id`),'editor-source','Original text gets keyboard focus');
  assert.equal(await evaluate(`document.getElementById('editor-image').hidden`),false);
  await until(()=>modalOpen && hitRegions.some(r=>r.width===1000 && r.height===740));
  assert.equal(await evaluate(`document.getElementById('editor-manga-ocr').hidden`),false);
  await until(()=>evaluate(`!document.getElementById('editor-manga-ocr').disabled`));
  const mangaPoint=await evaluate(`(()=>{const r=document.getElementById('editor-manga-ocr').getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`);
  win.webContents.sendInputEvent({type:'mouseMove',...mangaPoint});
  win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...mangaPoint});
  win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...mangaPoint});
  await until(()=>evaluate(`document.getElementById('editor-source').value==='今日はきっといい天気ですね。'`));
  assert.match(await evaluate(`document.getElementById('editor-translation-label').textContent`),/上次译文.*尚未重新翻译/);
  assert.equal(await evaluate(`document.querySelector('.copy').textContent`),current.text,'Manga OCR only changes the editable draft');
  await evaluate(`document.getElementById('editor-source').value=' ';document.getElementById('editor-save').click()`);
  assert.equal(translateCalls,0,'Empty text does not call provider');
  assert.equal(await evaluate(`document.getElementById('editor-error').hidden`),false);
  await evaluate(`document.getElementById('editor-reocr').click()`);
  await until(()=>evaluate(`document.getElementById('editor-source').value==='今日は本当にいい天気ですね。'`));
  assert.equal(await evaluate(`document.querySelector('.copy').textContent`),current.text,'Re-OCR changes the draft only');
  await evaluate(`document.getElementById('editor-save').click()`);
  await until(()=>evaluate(`!document.getElementById('editor-error').hidden && !document.getElementById('editor-save').disabled`));
  assert.equal(await evaluate(`document.querySelector('.copy').textContent`),current.text,'Provider failure keeps previous bubble');
  assert.equal(await evaluate(`document.getElementById('editor-source').value`),'今日は本当にいい天気ですね。');
  translateMode='success';await evaluate(`document.getElementById('editor-save').click()`);
  await until(()=>evaluate(`document.getElementById('editor-shell').hidden`));
  assert.deepEqual(lastPayload,{key:'editor-21',text:'今日は本当にいい天気ですね。'},'Save addresses only original bubble and text');
  assert.equal(await evaluate(`document.activeElement.className`),'edit','Save restores triggering control focus');
  assert(await evaluate(`document.querySelector('.bubble').classList.contains('showing-original')`),'Save preserves original-view mode');
  assert.deepEqual(await evaluate(`({x:document.querySelector('.bubble').offsetLeft,y:document.querySelector('.bubble').offsetTop})`),position,'Save preserves dragged position');
  await evaluate(`document.querySelector('.original').click()`);
  assert.equal(await evaluate(`document.querySelector('.copy').textContent`),current.translated);

  inspectionSource='en';await open();
  assert.equal(await evaluate(`document.getElementById('editor-manga-ocr').hidden`),false,'Explain Japanese-only mode instead of hiding the feature');
  assert.equal(await evaluate(`document.getElementById('editor-manga-ocr').disabled`),false);
  await until(()=>evaluate(`document.getElementById('editor-status').textContent.includes('仅支持日文气泡')`));
  assert.match(await evaluate(`document.getElementById('editor-status').textContent`),/仅支持日文气泡/);
  await evaluate(`document.getElementById('editor-manga-ocr').click()`);
  assert.match(await evaluate(`document.getElementById('editor-error').textContent`),/仅支持日文气泡/);
  await snapshot(win,'overlay-editor-non-ja.png');
  await evaluate(`document.getElementById('editor-cancel').click()`);
  inspectionSource='ja';mangaAvailable=false;await open();
  assert.equal(await evaluate(`document.getElementById('editor-manga-ocr').hidden`),false,'Explain missing optional model instead of hiding the feature');
  assert.equal(await evaluate(`document.getElementById('editor-manga-ocr').disabled`),false,'Missing model should return a reason instead of leaving an inert button');
  await until(()=>evaluate(`document.getElementById('editor-status').textContent.includes('模型未安装')`));
  await evaluate(`document.getElementById('editor-manga-ocr').click()`);
  await until(()=>evaluate(`document.getElementById('editor-error').textContent.includes('尚未安装')`));
  await snapshot(win,'overlay-editor-no-model.png');
  await evaluate(`document.getElementById('editor-cancel').click()`);
  mangaAvailable=true;

  const dismissCount=dismissedKeys.length;
  await send('begin',{...begin,job:22});
  assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),0,'Previous version stays hidden during replacement');
  await send('add',[{...base,job:22,key:'partial-22',translated:'部分译文'}]);
  await send('finish',{job:22,success:false,completed:1,total:2});
  await send('begin',{...begin,job:22,retry:true});
  assert.equal(await evaluate(`document.querySelector('.copy').textContent`),'部分译文','Retry preserves completed partial');
  await send('finish',{job:22,success:false,cancelled:true,completed:1,total:2});await send('restore',{job:22});
  assert.equal(await evaluate(`document.querySelector('.copy').textContent`),current.translated);
  assert.equal(dismissedKeys.length,dismissCount,'Snapshot detach and rollback never dismiss stored results');
  assert.deepEqual(await evaluate(`({x:document.querySelector('.bubble').offsetLeft,y:document.querySelector('.bubble').offsetTop})`),position,'Rollback preserves dragged position');
  await send('add',[{...base,job:22,id:1,key:'late-22'}]);
  assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),1,'Restored batch rejects late partials');
  await send('stale',{stale:true});assert.equal(await evaluate(`getComputedStyle(document.querySelector('.bubble')).visibility`),'hidden');
  await send('stale',{stale:false});assert.equal(await evaluate(`document.querySelector('.copy').textContent`),current.translated);

  translateMode='deferred';await open();await evaluate(`document.getElementById('editor-save').click()`);
  await until(()=>Boolean(resolveTranslate));await evaluate(`document.getElementById('editor-cancel').click()`);
  resolveTranslate({bubble:{...current,translated:'取消后迟到的译文'}});resolveTranslate=null;await delay(40);
  assert.equal(await evaluate(`document.querySelector('.copy').textContent`),current.translated,'Closing editor ignores late save result');
  await open();await evaluate(`document.getElementById('editor-save').click()`);await until(()=>Boolean(resolveTranslate));
  await send('clear');resolveTranslate({bubble:{...current,translated:'清除后迟到的译文'}});resolveTranslate=null;await delay(40);
  assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),0,'Clear during save never resurrects bubble');
  assert.equal(await evaluate(`document.getElementById('editor-shell').hidden`),true);
  await send('restore',{job:22});assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),0,'Clear also discards previous snapshot');

  current={...current,job:23,key:'editor-23'};await send('begin',{...begin,job:23});await send('add',[current]);
  inspectDeferred=true;await evaluate(`document.querySelector('.edit').click()`);await until(()=>Boolean(resolveInspect));
  await send('begin',{...begin,job:24});current={...current,job:24,key:'editor-24'};await send('add',[current]);
  resolveInspect(inspection());inspectDeferred=false;await delay(40);
  assert.equal(await evaluate(`document.getElementById('editor-shell').hidden`),true,'Replacement ignores late inspection');
  assert.equal(await evaluate(`document.querySelector('.bubble').dataset.key`),'editor-24');
  await open();
  await send('preferences',{glassTone:'clear'});
  assert(await evaluate(`parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--glass-bg').match(/([.\\d]+)\\s*\\)$/)[1]) <= .25`),'Clear glass keeps the background visible');
  await snapshot(win,'overlay-editor.png');
  await send('preferences',{glassTone:'tinted'});
  assert.equal(await evaluate(`document.documentElement.dataset.glassTone`),'tinted');
  await snapshot(win,'overlay-editor-tinted.png');
  win.setSize(420,560);await delay(50);
  assert(await evaluate(`(()=>{const r=document.getElementById('bubble-editor').getBoundingClientRect();return r.width<=innerWidth&&r.height<=innerHeight&&r.x>=0&&r.y>=0})()`));
  await snapshot(win,'overlay-editor-small.png');
  await evaluate(`document.getElementById('bubble-editor').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  assert.equal(await evaluate(`document.getElementById('editor-shell').hidden`),true);
  assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),1,'Editor Escape only closes modal');
  await evaluate(`document.querySelector('.bubble').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))`);
  await until(()=>dismissedKeys.includes('editor-24'));
  assert.equal(await evaluate(`document.querySelectorAll('.bubble').length`),0,'Bubble Escape dismisses result');
  await send('clear');
  ipcMain.removeListener('overlay:editor',modalListener);ipcMain.removeListener('win:hitRegions',hitsListener);
  for(const name of ['frame:health','bubble:inspect','bubble:ocr','bubble:manga-ocr','bubble:translate']) ipcMain.removeHandler(name);
}

async function testFrame() {
  let finish,frame,lockCalls=0,retryCalls=0,restoreCalls=0,recenterCalls=0,readingFallback=false;
  ipcMain.handle('frame:health',()=>({ocr:'ready',providers:{deepseek:true,google:true,claude:false}}));
  ipcMain.handle('frame:lock',()=>{lockCalls++;return new Promise(resolve=>{finish=resolve;});});
  ipcMain.handle('frame:cancel',()=>finish({cancelled:true}));
  ipcMain.handle('frame:clear',()=>finish?.({cancelled:true}));
  ipcMain.handle('frame:reveal',()=>false);
  ipcMain.handle('frame:retry',()=>{retryCalls++;return {count:2};});
  ipcMain.handle('frame:restore',()=>{restoreCalls++;return {restored:true,count:6};});
  ipcMain.handle('frame:readingMode',(_event,value)=>readingFallback ? {mode:'fixed',error:'测试：当前系统无法检测翻页'} : {mode:value});
  ipcMain.handle('frame:recenter',()=>{recenterCalls++;return {};});
  const heightListener=(event,height)=>{if(frame && event.sender===frame.webContents) frame.setSize(680,Math.max(160,Math.min(640,height)));};
  ipcMain.on('frame:height',heightListener);
  frame=new BrowserWindow({width:680,height:400,show:false,frame:false,webPreferences:{backgroundThrottling:false,preload:path.join(root,'preload.js')}});
  await frame.loadFile(path.join(root,'renderer/frame.html'));
  const evaluate=c=>frame.webContents.executeJavaScript(c,true);
  await until(()=>evaluate(`document.getElementById('status').textContent==='框选漫画后开始翻译'`));
  assert.equal(await evaluate(`document.querySelectorAll('.resize-handle').length`),0,'Toolbar does not contain selection resize handles');
  assert.equal(frame.getBounds().width,680);
  await snapshot(frame,'frame.png');
  await evaluate(`document.getElementById('lock').click()`);
  assert.equal(await evaluate(`document.querySelector('#lock span').textContent`),'取消翻译');
  await until(()=>Boolean(finish));
  await evaluate(`document.getElementById('lock').click()`);await delay(30);
  assert.equal(await evaluate(`document.getElementById('status').textContent`),'已取消');
  finish=null;await evaluate(`document.getElementById('lock').click()`);await until(()=>Boolean(finish));
  finish({error:'测试：网络中断，请重试'});await delay(30);
  assert.equal(await evaluate(`document.getElementById('message').hidden`),false);
  assert.equal(await evaluate(`document.querySelector('#message p').textContent`),'测试：网络中断，请重试');
  frame.webContents.send('frame:recovery',{available:true,canRestore:true,completed:4,total:6});await delay(50);
  assert.equal(await evaluate(`document.getElementById('recoveryCount').textContent`),'本页完成 4 / 6');
  assert.equal(await evaluate(`document.getElementById('retryRemaining').disabled`),false);
  assert.equal(await evaluate(`document.getElementById('restorePrevious').disabled`),false);
  assert(await evaluate(`document.getElementById('message').getBoundingClientRect().top>=document.getElementById('recovery').getBoundingClientRect().bottom`),'Failure message leaves recovery buttons visible');
  assert(await evaluate(`Array.from(document.querySelectorAll('button,select')).filter(e=>e.getClientRects().length).every(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.bottom<=innerHeight})`),'Fixed-width toolbar controls fit with recovery and error');
  await snapshot(frame,'frame-recovery.png');
  await evaluate(`document.getElementById('retryRemaining').click()`);await until(()=>retryCalls===1);
  await until(()=>evaluate(`document.querySelector('#lock span').textContent==='翻译选区'`));
  assert.equal(await evaluate(`document.getElementById('message').hidden`),true,'Retry clears old error');
  await evaluate(`document.getElementById('restorePrevious').click()`);await until(()=>restoreCalls===1);
  await until(()=>evaluate(`document.getElementById('status').textContent==='已恢复上一版 · 6 处'`));
  frame.webContents.send('frame:recovery',{available:false,canRestore:false,completed:0,total:0});await delay(30);
  assert.equal(await evaluate(`document.getElementById('recovery').hidden`),true);
  await evaluate(`document.getElementById('watchMode').click()`);await delay(30);
  assert.equal(await evaluate(`document.getElementById('watchMode').getAttribute('aria-pressed')`),'true');
  const beforeStable=lockCalls;
  frame.webContents.send('frame:readingState',{state:'stable',text:'画面已稳定，点击翻译新页'});await delay(40);
  assert.equal(await evaluate(`document.getElementById('translateCurrent').hidden`),false);
  assert.equal(lockCalls,beforeStable,'Stable page never calls translation automatically');
  finish=null;await evaluate(`document.getElementById('translateCurrent').click()`);await until(()=>Boolean(finish));
  assert.equal(lockCalls,beforeStable+1);
  finish({count:6});await until(()=>evaluate(`document.querySelector('#lock span').textContent==='翻译选区'`));
  readingFallback=true;await evaluate(`document.getElementById('watchMode').click()`);await delay(30);
  assert.equal(await evaluate(`document.getElementById('fixedMode').getAttribute('aria-pressed')`),'true');
  assert.equal(await evaluate(`JSON.parse(localStorage.getItem('preferences')).readingMode`),'fixed');
  assert.equal(await evaluate(`document.querySelector('.reading-row').dataset.state`),'error');
  await evaluate(`document.getElementById('glassTone').value='tinted';document.getElementById('glassTone').dispatchEvent(new Event('change'))`);
  assert.equal(await evaluate(`document.documentElement.dataset.glassTone`),'tinted');
  await evaluate(`document.getElementById('dismissMessage').click();document.getElementById('moveSelection').click()`);await until(()=>recenterCalls===1);
  assert.equal(frame.getBounds().width,680,'Moving selection preserves toolbar width');
  await snapshot(frame,'frame-tinted.png');
  ipcMain.removeListener('frame:height',heightListener);
  frame.close();
}
